spring:
  thymeleaf:
    cache: false
    prefix: classpath:templates/
    check-template-location: true
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  freemarker:
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://ldfs-d2p-2.cmeoxjdrt43c.ap-northeast-2.rds.amazonaws.com:3306/dpp?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: ldfs2021$%
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connectionTimeout: 30000
      maximumPoolSize: 10
      maxLifetime: 3600000
      poolName: HikariCP
      readOnly: false
      connectionTestQuery: SELECT 1
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1

server:
  error:
    include-message: always
    include-binding-errors: always
  port: 80
  tomcat:
    remoteip:
      remote-ip-header: "x-forwarded-for"
      protocol-header: "x-forwarded-proto"

logging:
  level:
    root: debug